# Скрываем версию Nginx (Security)
server_tokens off;

# Защита от DDoS: 10 запросов в секунду с одного IP
limit_req_zone $binary_remote_addr zone=api_limit:10m rate=10r/s;

# SECURITY HEADERS (Харденинг)
add_header X-Frame-Options "SAMEORIGIN" always;
add_header X-Content-Type-Options "nosniff" always;
add_header X-XSS-Protection "1; mode=block" always;
add_header Content-Security-Policy "default-src 'self';" always;

# Имена ДОЛЖНЫ совпадать с именами сервисов в docker-compose.yml
upstream order_api {
    server order_service:8080;
}
upstream inv_api {
    server inventory_service:8081; # Порт должен совпадать с INVENTORY_PORT
}

server {
    listen 80;

    # Лимит размера файла (для Slicer)
    client_max_body_size 300M;

    # Проброс правильных заголовков во все location
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    location /api/orders {
        limit_req zone=api_limit burst=20 nodelay;
        proxy_pass http://order_api; # БЕЗ СЛЕША НА КОНЦЕ!
    }

    location /api/inventory {
        limit_req zone=api_limit burst=20 nodelay;
        proxy_pass http://inv_api; # БЕЗ СЛЕША НА КОНЦЕ!
    }

    # Healthcheck самого Nginx (DevOps практика)
    location /health {
        access_log off;
        return 200 "Gateway is ALIVE\n";
    }
}
